server:
  contextPath: /peas-be

spring:
  datasource:
    url: jdbc:mysql://dburl:3306/peas?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf-8
    username: peas
    password: password
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
    sqlScriptEncoding: UTF-8
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true

security:
  basic:
    enabled: false

settings:
  frontendUrl: https://c11.media.hosei.ac.jp/peas
  #for dev
  wildcardCORSOrigin: true
  adminPassword: adminPassword
